# Generated by Django 5.1.6 on 2025-05-04 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Plate Number')),
                ('car_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('TRUCK', 'Truck'), ('VAN', 'Van')], max_length=10, verbose_name='Car Type')),
                ('insurance', models.CharField(max_length=100, verbose_name='Insurance')),
                ('insurance_expiry_date', models.DateField(verbose_name='Insurance Expiry Date')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('car_serial_number', models.CharField(max_length=100, unique=True, verbose_name='Car Serial Number')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.driver', verbose_name='Driver')),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.vendor', verbose_name='Vendor')),
            ],
        ),
    ]
